### ISSUE TITLE
Script adding body. to every field

### ISSUE THREAD

**Issue by jasc22** [dgunter/evtxtoelk#1]
Hi, thanks for the tool. When I use the tool to import the data, it's adding "body." to every field. Is it possible to remove this entry?

![image](https://user-images.githubusercontent.com/29802479/57658189-d8885880-7592-11e9-963b-9544300c6be8.png)

**Comment by dgunter** [comment]
Let me take a look and get back to you in the next few days. I know this was by design in a past version. Let me see what we ended up getting in with the current version.

**Comment by RuadhriM** [comment]
Any update on this?

**Comment by dgunter** [comment]
@RuadhriM and @jasc22 : Should be good to go with the commit a few seconds ago. Let me know if you spot any issues.

![Screen Shot 2019-08-02 at 3 14 51 PM](https://user-images.githubusercontent.com/3322002/62396269-57f54a80-b538-11e9-8c02-9f95e0f10d40.png)
