### ISSUE TITLE
Had to comment out _type field

### ISSUE THREAD

**Issue by reswob10** [dgunter/evtxtoelk#5]
I just used this tool on linux to import into and ELK stack.  Works great, but I had to comment out the line that assigned a _type field because it Elasticsearch said that field value was invalid.  This is with ES 8.3.3

Otherwise, works great.

**Comment by alex87fr** [comment]
The same....
But how to replace "_type" please ?

its working great.

**Comment by joseraeiro** [comment]
Yes, could you please explain with more detail how (and where) were you able to comment out the line that assigned a _type field.

**Comment by dgunter** [comment]
Going to fix this issue this week with issue #6. It's an ELK 8 change we need to make on our end.
